### PR TITLE
Move WP files to a subdir

### PR DESCRIPTION
**Pull request by szepeviktor**
From #1 

Steps :)

1. Switch to TwentyTwenty theme
1. Remove existing getting-started-theme
1. Clone from my branch: `git clone -b subdir https://github.com/szepeviktor/getting-started-theme.git`
1. Get packages: `composer update`
1. Switch to getting-started-theme
1. Benefit!

@gchtr

### CODE REVIEW

**Comment by szepeviktor** [comment]
What a nice little home for our template 🥰 

kép

**Comment by szepeviktor** [comment]
We should figure out what to do with `views`!

1. keep it in the root
1. move it to `template/`

**Comment by jarednova** [comment]
@szepeviktor see my response with #1 — let's pick this up in https://github.com/timber/starter-theme/pull/103

**Comment by szepeviktor** [comment]
This will be implemented in https://github.com/timber/getting-started-theme/pull/3

**Comment by szepeviktor** [comment]
This will be implemented in https://github.com/timber/starter-theme/pull/103

**Pull request closed without merging**
